# Generated by Django 4.2.17 on 2025-01-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_property', '0002_room_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='postcode',
        ),
    ]
