# Generated by Django 4.2.17 on 2025-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_property', '0004_room_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/images/'),
        ),
    ]
