# Generated by Django 4.2.17 on 2025-02-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_property', '0007_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
    ]
