# Generated by Django 4.2.17 on 2025-01-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_account', '0002_landlordprofile_room_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
