# Generated by Django 4.2.17 on 2024-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_account', '0002_landlordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
