# Generated by Django 4.2.17 on 2025-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_account', '0003_remove_property_landlord_delete_room_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
