# Generated by Django 4.2.17 on 2025-01-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_account', '0003_landlordprofile_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='properties_owned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
